name: hsfm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - xmltodict
  - bokeh
  - pip
  - gdal
  - scipy
  - haversine
  - utm
  - panel
  - holoviews
  - geoviews
  - seaborn
  - opencv
  - rasterstats
  - hvplot
  - rasterio
  - scikit-image
  - xarray
  - datashader
  - pandas
  - s3fs
  - pdal
  - py3dep
  - pypdf2
  - gdown
  - pystac-client
  - planetary-computer
  - pip:
    - elevation
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/friedrichknuth/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/dshean/imview.git#egg=imview"
    - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"
    - "--editable=git+https://github.com/friedrichknuth/hipp.git#egg=hipp"