name: hsfm_test
channels:
  - nasa-ames-stereo-pipeline
  - usgs-astrogeology
  - conda-forge
dependencies:
  - stereo-pipeline
  - xdem  # brings: numpy, scipy, rasterio, xarray, matplotlib, gdal
  - geopandas  # brings: shapely, pandas
  - descartes
  - contextily
  - xmltodict
  - bokeh
  - haversine
  - utm
  - panel
  - holoviews
  - geoviews
  - seaborn
  - opencv
  - rasterstats
  - hvplot
  - scikit-image
  - datashader
  - s3fs
  - pdal
  - py3dep
  - pypdf2
  - gdown
  - pystac-client
  - planetary-computer
  - tree
  - pip
  - pip:
    - elevation
    - pygeotools @ git+https://github.com/dshean/pygeotools.git
    - demcoreg @ git+https://github.com/friedrichknuth/demcoreg.git  # scripts enabled by default on this fork
    - imview @ git+https://github.com/dshean/imview.git
    - bare @ git+https://github.com/friedrichknuth/bare.git
    - hipp @ git+https://github.com/friedrichknuth/hipp.git
    - -e .  # Install hsfm package in editable mode