name: hsfm
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - xmltodict
  - bokeh=1.3.4
  - pip
  - gdal
  - scipy
  - haversine
  - utm
  - panel
  - holoviews
  - geoviews
  - seaborn
  - opencv
  - rasterstats
  - hvplot
  - rasterstats
  - rasterio
  - scikit-image
  - xarray
  - datashader
  - pandas
  - pip:
    - elevation
    - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
    - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
    - "--editable=git+https://github.com/dshean/imview.git#egg=imview"
    - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"
    - "--editable=git+https://github.com/friedrichknuth/hipp.git#egg=hipp"
    - "--editable=git+https://github.com/friedrichknuth/driveanon.git#egg=driveanon"
    - black
    - pre-commit

